### ISSUE TITLE
Consider rename of `config.scala` file

### ISSUE THREAD

**Issue by kpodsiad** [Odomontois/evo-derivation#23]
By default, mac os filesystem is case insensitive so files like `Config.scala` and `config.scala` are treated as the same file.

Of course, this issue can be solved on user side - they need to create another partition which will be case sensitive but it can be a bit of ceremony for users which use company provided macbooks.

**Comment by Odomontois** [comment]
Ok, I've fixed it in the direct commit. Fell into the same trap on a new MacBook.
